# Generated by Django 3.0.4 on 2020-03-12 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plants', '0001_initial'),
        ('species', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='Owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_plants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='plant',
            name='specie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='species.Specie'),
        ),
    ]
