# Generated by Django 3.0.6 on 2020-07-22 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=50)),
                ('specie', models.CharField(max_length=100, null=True)),
                ('location', models.CharField(max_length=150)),
                ('info', models.CharField(max_length=200)),
                ('last_watered', models.DateField()),
                ('last_fertilized', models.DateField()),
                ('watering_interval', models.IntegerField()),
                ('fertilizing_interval', models.IntegerField()),
            ],
        ),
    ]
